### ISSUE TITLE
location of steamcmd.sh

### ISSUE THREAD

**Issue by CaptSpify** [LorenDB/download-steam-games#1]
Where can I find the steamcmd.sh command that it's looking for in the below error?

`std.process.ProcessException@std/process.d(1196): Failed to execute '/usr/games//steamcmd.sh' (No such file or directory)`

Thanks!

**Comment by LorenDB** [comment]
You have to install [SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD) on your system and specify the path to it. If download-steam-games doesn't prompt you for the path to steamcmd, you can manually edit `~/.config/download-steam-games/config.json` to add it.

**Comment by LorenDB** [comment]
I just updated the README with clearer instructions for installation and usage.
